import { create } from "zustand";
import type {
  AdminUser,
  UserRecord,
  VerificationRequest,
  Report,
  Subscription,
  AdminStats,
  ActivityLogEntry,
} from "@/types/admin";

/* ============================================================
   Mock Data
   ============================================================ */

const mockUsers: UserRecord[] = [
  {
    id: "u1",
    fullName: "Priya Subramanian",
    email: "priya.s@email.com",
    phone: "+91 98765 43210",
    gender: "female",
    age: 27,
    community: "Iyer",
    location: "Chennai",
    plan: "premium_6",
    status: "active",
    isVerified: true,
    reportsCount: 0,
    profileComplete: 95,
    joinedAt: "2025-08-15",
    lastActive: "2026-03-09",
    interestsSent: 24,
    interestsReceived: 42,
    profileViews: 318,
    lastLoginIp: "103.21.58.193",
  },
  {
    id: "u2",
    fullName: "Karthik Rajan",
    email: "karthik.r@email.com",
    phone: "+91 87654 32109",
    gender: "male",
    age: 30,
    community: "Iyengar",
    location: "Bangalore",
    plan: "free",
    status: "active",
    isVerified: false,
    reportsCount: 1,
    profileComplete: 80,
    joinedAt: "2025-10-02",
    lastActive: "2026-03-08",
    interestsSent: 15,
    interestsReceived: 8,
    profileViews: 120,
    lastLoginIp: "49.207.12.87",
  },
  {
    id: "u3",
    fullName: "Meenakshi Venkat",
    email: "meenakshi.v@email.com",
    phone: "+91 76543 21098",
    gender: "female",
    age: 25,
    community: "Mudaliar",
    location: "Coimbatore",
    plan: "premium_3",
    status: "active",
    isVerified: true,
    reportsCount: 0,
    profileComplete: 100,
    joinedAt: "2025-11-20",
    lastActive: "2026-03-09",
    interestsSent: 30,
    interestsReceived: 55,
    profileViews: 410,
    lastLoginIp: "122.165.48.22",
  },
  {
    id: "u4",
    fullName: "Arun Kumar",
    email: "arun.k@email.com",
    phone: "+91 65432 10987",
    gender: "male",
    age: 32,
    community: "Nadar",
    location: "Madurai",
    plan: "free",
    status: "suspended",
    isVerified: false,
    reportsCount: 3,
    profileComplete: 60,
    joinedAt: "2025-09-10",
    lastActive: "2026-02-15",
    interestsSent: 48,
    interestsReceived: 2,
    profileViews: 35,
    lastLoginIp: "59.90.143.67",
  },
  {
    id: "u5",
    fullName: "Divya Krishnan",
    email: "divya.k@email.com",
    phone: "+91 54321 09876",
    gender: "female",
    age: 28,
    community: "Pillai",
    location: "Trichy",
    plan: "premium_12",
    status: "active",
    isVerified: true,
    reportsCount: 0,
    profileComplete: 90,
    joinedAt: "2025-07-05",
    lastActive: "2026-03-09",
    interestsSent: 18,
    interestsReceived: 63,
    profileViews: 520,
    lastLoginIp: "14.139.220.5",
  },
  {
    id: "u6",
    fullName: "Rajesh Iyer",
    email: "rajesh.i@email.com",
    phone: "+91 43210 98765",
    gender: "male",
    age: 35,
    community: "Iyer",
    location: "Hyderabad",
    plan: "free",
    status: "banned",
    isVerified: false,
    reportsCount: 5,
    profileComplete: 45,
    joinedAt: "2025-12-01",
    lastActive: "2026-01-20",
    interestsSent: 72,
    interestsReceived: 0,
    profileViews: 15,
    lastLoginIp: "182.73.14.201",
  },
  {
    id: "u7",
    fullName: "Lakshmi Narayanan",
    email: "lakshmi.n@email.com",
    phone: "+91 32109 87654",
    gender: "female",
    age: 26,
    community: "Chettiar",
    location: "Salem",
    plan: "premium_6",
    status: "active",
    isVerified: true,
    reportsCount: 0,
    profileComplete: 88,
    joinedAt: "2025-10-15",
    lastActive: "2026-03-08",
    interestsSent: 12,
    interestsReceived: 38,
    profileViews: 275,
    lastLoginIp: "103.88.45.92",
  },
  {
    id: "u8",
    fullName: "Senthil Murugan",
    email: "senthil.m@email.com",
    phone: "+91 21098 76543",
    gender: "male",
    age: 29,
    community: "Gounder",
    location: "Erode",
    plan: "free",
    status: "active",
    isVerified: false,
    reportsCount: 0,
    profileComplete: 70,
    joinedAt: "2026-01-08",
    lastActive: "2026-03-07",
    interestsSent: 9,
    interestsReceived: 5,
    profileViews: 65,
    lastLoginIp: "27.57.210.44",
  },
  {
    id: "u9",
    fullName: "Anitha Balachander",
    email: "anitha.b@email.com",
    phone: "+91 91234 56789",
    gender: "female",
    age: 24,
    community: "Iyer",
    location: "Chennai",
    plan: "free",
    status: "active",
    isVerified: false,
    reportsCount: 0,
    profileComplete: 55,
    joinedAt: "2026-02-10",
    lastActive: "2026-03-09",
    interestsSent: 3,
    interestsReceived: 12,
    profileViews: 88,
    lastLoginIp: "103.21.58.45",
  },
  {
    id: "u10",
    fullName: "Vijay Shankar",
    email: "vijay.s@email.com",
    phone: "+91 82345 67890",
    gender: "male",
    age: 31,
    community: "Iyengar",
    location: "Bangalore",
    plan: "premium_3",
    status: "active",
    isVerified: true,
    reportsCount: 0,
    profileComplete: 92,
    joinedAt: "2025-12-15",
    lastActive: "2026-03-09",
    interestsSent: 22,
    interestsReceived: 14,
    profileViews: 180,
    lastLoginIp: "49.207.18.33",
  },
  {
    id: "u11",
    fullName: "Deepa Ranganathan",
    email: "deepa.r@email.com",
    phone: "+91 73456 78901",
    gender: "female",
    age: 29,
    community: "Mudaliar",
    location: "Madurai",
    plan: "free",
    status: "active",
    isVerified: false,
    reportsCount: 0,
    profileComplete: 65,
    joinedAt: "2026-01-22",
    lastActive: "2026-03-08",
    interestsSent: 6,
    interestsReceived: 20,
    profileViews: 145,
    lastLoginIp: "59.90.22.156",
  },
  {
    id: "u12",
    fullName: "Ramesh Sundaram",
    email: "ramesh.s@email.com",
    phone: "+91 64567 89012",
    gender: "male",
    age: 34,
    community: "Chettiar",
    location: "Coimbatore",
    plan: "premium_6",
    status: "active",
    isVerified: true,
    reportsCount: 0,
    profileComplete: 85,
    joinedAt: "2025-09-25",
    lastActive: "2026-03-07",
    interestsSent: 35,
    interestsReceived: 18,
    profileViews: 210,
    lastLoginIp: "122.165.55.78",
  },
  {
    id: "u13",
    fullName: "Kavitha Moorthy",
    email: "kavitha.m@email.com",
    phone: "+91 55678 90123",
    gender: "female",
    age: 27,
    community: "Nadar",
    location: "Tirunelveli",
    plan: "free",
    status: "active",
    isVerified: false,
    reportsCount: 0,
    profileComplete: 72,
    joinedAt: "2026-02-01",
    lastActive: "2026-03-06",
    interestsSent: 4,
    interestsReceived: 16,
    profileViews: 95,
    lastLoginIp: "14.139.215.88",
  },
  {
    id: "u14",
    fullName: "Suresh Babu",
    email: "suresh.b@email.com",
    phone: "+91 46789 01234",
    gender: "male",
    age: 28,
    community: "Pillai",
    location: "Chennai",
    plan: "free",
    status: "active",
    isVerified: false,
    reportsCount: 0,
    profileComplete: 50,
    joinedAt: "2026-02-20",
    lastActive: "2026-03-05",
    interestsSent: 7,
    interestsReceived: 3,
    profileViews: 40,
    lastLoginIp: "103.21.60.112",
  },
  {
    id: "u15",
    fullName: "Sangeetha Ravi",
    email: "sangeetha.r@email.com",
    phone: "+91 37890 12345",
    gender: "female",
    age: 26,
    community: "Gounder",
    location: "Erode",
    plan: "premium_3",
    status: "active",
    isVerified: true,
    reportsCount: 0,
    profileComplete: 97,
    joinedAt: "2025-11-05",
    lastActive: "2026-03-09",
    interestsSent: 20,
    interestsReceived: 48,
    profileViews: 380,
    lastLoginIp: "27.57.198.67",
  },
  {
    id: "u16",
    fullName: "Manoj Prabhu",
    email: "manoj.p@email.com",
    phone: "+91 28901 23456",
    gender: "male",
    age: 33,
    community: "Iyer",
    location: "Trichy",
    plan: "free",
    status: "inactive",
    isVerified: false,
    reportsCount: 0,
    profileComplete: 30,
    joinedAt: "2025-11-28",
    lastActive: "2025-12-10",
    interestsSent: 0,
    interestsReceived: 1,
    profileViews: 8,
    lastLoginIp: "14.139.225.34",
  },
  {
    id: "u17",
    fullName: "Nithya Ganesh",
    email: "nithya.g@email.com",
    phone: "+91 19012 34567",
    gender: "female",
    age: 25,
    community: "Iyengar",
    location: "Bangalore",
    plan: "premium_12",
    status: "active",
    isVerified: true,
    reportsCount: 0,
    profileComplete: 98,
    joinedAt: "2025-08-20",
    lastActive: "2026-03-09",
    interestsSent: 28,
    interestsReceived: 71,
    profileViews: 640,
    lastLoginIp: "49.207.25.88",
  },
  {
    id: "u18",
    fullName: "Prakash Thiagarajan",
    email: "prakash.t@email.com",
    phone: "+91 90123 45678",
    gender: "male",
    age: 30,
    community: "Mudaliar",
    location: "Salem",
    plan: "free",
    status: "active",
    isVerified: false,
    reportsCount: 1,
    profileComplete: 68,
    joinedAt: "2026-01-15",
    lastActive: "2026-03-08",
    interestsSent: 14,
    interestsReceived: 6,
    profileViews: 52,
    lastLoginIp: "103.88.50.44",
  },
  {
    id: "u19",
    fullName: "Vani Krishnamurthy",
    email: "vani.k@email.com",
    phone: "+91 81234 56780",
    gender: "female",
    age: 30,
    community: "Iyer",
    location: "Hyderabad",
    plan: "premium_6",
    status: "active",
    isVerified: true,
    reportsCount: 0,
    profileComplete: 91,
    joinedAt: "2025-10-08",
    lastActive: "2026-03-09",
    interestsSent: 16,
    interestsReceived: 34,
    profileViews: 290,
    lastLoginIp: "182.73.20.99",
  },
  {
    id: "u20",
    fullName: "Ganesh Ramanujam",
    email: "ganesh.r@email.com",
    phone: "+91 72345 67891",
    gender: "male",
    age: 27,
    community: "Chettiar",
    location: "Coimbatore",
    plan: "free",
    status: "active",
    isVerified: false,
    reportsCount: 0,
    profileComplete: 58,
    joinedAt: "2026-02-25",
    lastActive: "2026-03-09",
    interestsSent: 5,
    interestsReceived: 2,
    profileViews: 28,
    lastLoginIp: "122.165.60.11",
  },
  {
    id: "u21",
    fullName: "Revathi Sundaresan",
    email: "revathi.s@email.com",
    phone: "+91 63456 78902",
    gender: "female",
    age: 23,
    community: "Pillai",
    location: "Chennai",
    plan: "free",
    status: "active",
    isVerified: false,
    reportsCount: 0,
    profileComplete: 42,
    joinedAt: "2026-03-01",
    lastActive: "2026-03-08",
    interestsSent: 1,
    interestsReceived: 8,
    profileViews: 55,
    lastLoginIp: "103.21.62.78",
  },
  {
    id: "u22",
    fullName: "Balaji Natarajan",
    email: "balaji.n@email.com",
    phone: "+91 54567 89013",
    gender: "male",
    age: 36,
    community: "Nadar",
    location: "Madurai",
    plan: "premium_3",
    status: "active",
    isVerified: true,
    reportsCount: 0,
    profileComplete: 82,
    joinedAt: "2025-12-10",
    lastActive: "2026-03-09",
    interestsSent: 19,
    interestsReceived: 10,
    profileViews: 155,
    lastLoginIp: "59.90.145.23",
  },
  {
    id: "u23",
    fullName: "Sowmya Venkatesh",
    email: "sowmya.v@email.com",
    phone: "+91 45678 90124",
    gender: "female",
    age: 28,
    community: "Gounder",
    location: "Erode",
    plan: "free",
    status: "suspended",
    isVerified: false,
    reportsCount: 2,
    profileComplete: 75,
    joinedAt: "2025-11-12",
    lastActive: "2026-02-28",
    interestsSent: 10,
    interestsReceived: 22,
    profileViews: 160,
    lastLoginIp: "27.57.205.91",
  },
  {
    id: "u24",
    fullName: "Harish Chandran",
    email: "harish.c@email.com",
    phone: "+91 36789 01235",
    gender: "male",
    age: 29,
    community: "Iyer",
    location: "Bangalore",
    plan: "free",
    status: "active",
    isVerified: false,
    reportsCount: 0,
    profileComplete: 63,
    joinedAt: "2026-01-30",
    lastActive: "2026-03-07",
    interestsSent: 11,
    interestsReceived: 4,
    profileViews: 38,
    lastLoginIp: "49.207.30.56",
  },
];

const mockVerifications: VerificationRequest[] = [
  {
    id: "v1",
    userId: "u2",
    userName: "Karthik Rajan",
    documentType: "aadhaar",
    documentUrl: "/mock/doc-aadhaar.jpg",
    selfieUrl: "/mock/selfie-karthik.jpg",
    status: "pending",
    submittedAt: "2026-03-07",
  },
  {
    id: "v2",
    userId: "u8",
    userName: "Senthil Murugan",
    documentType: "driving_license",
    documentUrl: "/mock/doc-dl.jpg",
    selfieUrl: "/mock/selfie-senthil.jpg",
    status: "pending",
    submittedAt: "2026-03-08",
  },
  {
    id: "v3",
    userId: "u1",
    userName: "Priya Subramanian",
    documentType: "passport",
    documentUrl: "/mock/doc-passport.jpg",
    selfieUrl: "/mock/selfie-priya.jpg",
    status: "approved",
    submittedAt: "2025-12-10",
    reviewedAt: "2025-12-12",
    reviewedBy: "Admin",
  },
  {
    id: "v4",
    userId: "u6",
    userName: "Rajesh Iyer",
    documentType: "voter_id",
    documentUrl: "/mock/doc-voter.jpg",
    selfieUrl: "/mock/selfie-rajesh.jpg",
    status: "rejected",
    submittedAt: "2025-12-20",
    reviewedAt: "2025-12-22",
    reviewedBy: "Admin",
    rejectionReason: "Document image is blurry and unreadable",
  },
];

const mockReports: Report[] = [
  {
    id: "r1",
    reportedUserId: "u4",
    reportedUserName: "Arun Kumar",
    reportedByUserId: "u1",
    reportedByUserName: "Priya Subramanian",
    reason: "harassment",
    description: "Sent multiple inappropriate messages after declining interest",
    status: "open",
    createdAt: "2026-03-06",
  },
  {
    id: "r2",
    reportedUserId: "u6",
    reportedUserName: "Rajesh Iyer",
    reportedByUserId: "u3",
    reportedByUserName: "Meenakshi Venkat",
    reason: "fake_profile",
    description: "Profile photos appear to be stolen from another person",
    status: "open",
    createdAt: "2026-03-05",
  },
  {
    id: "r3",
    reportedUserId: "u4",
    reportedUserName: "Arun Kumar",
    reportedByUserId: "u5",
    reportedByUserName: "Divya Krishnan",
    reason: "spam",
    description: "Sending mass copy-paste messages to all female users",
    status: "open",
    createdAt: "2026-03-04",
  },
  {
    id: "r4",
    reportedUserId: "u6",
    reportedUserName: "Rajesh Iyer",
    reportedByUserId: "u7",
    reportedByUserName: "Lakshmi Narayanan",
    reason: "inappropriate_photos",
    description: "Uploaded inappropriate content as profile photos",
    status: "resolved",
    createdAt: "2026-02-20",
    resolvedAt: "2026-02-22",
    resolution: "User banned after review",
  },
];

const mockSubscriptions: Subscription[] = [
  {
    id: "s1",
    userId: "u1",
    userName: "Priya Subramanian",
    plan: "premium_6",
    amount: 4494,
    startDate: "2025-12-01",
    endDate: "2026-06-01",
    status: "active",
    paymentMethod: "UPI",
  },
  {
    id: "s2",
    userId: "u3",
    userName: "Meenakshi Venkat",
    plan: "premium_3",
    amount: 2697,
    startDate: "2026-01-15",
    endDate: "2026-04-15",
    status: "active",
    paymentMethod: "Card",
  },
  {
    id: "s3",
    userId: "u5",
    userName: "Divya Krishnan",
    plan: "premium_12",
    amount: 7188,
    startDate: "2025-09-01",
    endDate: "2026-09-01",
    status: "active",
    paymentMethod: "Net Banking",
  },
  {
    id: "s4",
    userId: "u7",
    userName: "Lakshmi Narayanan",
    plan: "premium_6",
    amount: 4494,
    startDate: "2025-11-01",
    endDate: "2026-05-01",
    status: "active",
    paymentMethod: "UPI",
  },
  {
    id: "s5",
    userId: "u10",
    userName: "Vijay Shankar",
    plan: "premium_3",
    amount: 2697,
    startDate: "2026-01-01",
    endDate: "2026-04-01",
    status: "active",
    paymentMethod: "Card",
  },
  {
    id: "s6",
    userId: "u12",
    userName: "Ramesh Sundaram",
    plan: "premium_6",
    amount: 4494,
    startDate: "2025-10-15",
    endDate: "2026-04-15",
    status: "active",
    paymentMethod: "UPI",
  },
  {
    id: "s7",
    userId: "u15",
    userName: "Sangeetha Ravi",
    plan: "premium_3",
    amount: 2697,
    startDate: "2025-12-01",
    endDate: "2026-03-01",
    status: "expired",
    paymentMethod: "Card",
  },
  {
    id: "s8",
    userId: "u17",
    userName: "Nithya Ganesh",
    plan: "premium_12",
    amount: 7188,
    startDate: "2025-09-15",
    endDate: "2026-09-15",
    status: "active",
    paymentMethod: "Net Banking",
  },
  {
    id: "s9",
    userId: "u19",
    userName: "Vani Krishnamurthy",
    plan: "premium_6",
    amount: 4494,
    startDate: "2025-11-10",
    endDate: "2026-05-10",
    status: "active",
    paymentMethod: "UPI",
  },
  {
    id: "s10",
    userId: "u22",
    userName: "Balaji Natarajan",
    plan: "premium_3",
    amount: 2697,
    startDate: "2026-01-20",
    endDate: "2026-04-20",
    status: "active",
    paymentMethod: "Card",
  },
];

const mockStats: AdminStats = {
  totalUsers: 12847,
  activeToday: 3421,
  pendingVerifications: 2,
  openReports: 3,
  monthlyRevenue: 284500,
  newUsersThisWeek: 156,
  totalPremiumUsers: 2341,
  freeUsers: 10506,
  maleUsers: 6810,
  femaleUsers: 6037,
  conversionRate: 18.2,
  avgProfileCompletion: 72,
};

const mockActivity: ActivityLogEntry[] = [
  {
    id: "a1",
    action: "user_registered",
    description: "New user registered",
    timestamp: "2026-03-09T10:30:00",
    userId: "u8",
    userName: "Senthil Murugan",
  },
  {
    id: "a2",
    action: "verification_submitted",
    description: "Verification request submitted",
    timestamp: "2026-03-08T14:20:00",
    userId: "u8",
    userName: "Senthil Murugan",
  },
  {
    id: "a3",
    action: "report_filed",
    description: "User reported for harassment",
    timestamp: "2026-03-06T09:15:00",
    userId: "u4",
    userName: "Arun Kumar",
  },
  {
    id: "a4",
    action: "subscription_purchased",
    description: "Premium 6-month plan purchased",
    timestamp: "2026-03-05T16:45:00",
    userId: "u7",
    userName: "Lakshmi Narayanan",
  },
  {
    id: "a5",
    action: "user_banned",
    description: "User banned after multiple reports",
    timestamp: "2026-02-22T11:00:00",
    userId: "u6",
    userName: "Rajesh Iyer",
  },
  {
    id: "a6",
    action: "premium_upgrade",
    description: "Upgraded to Premium 12M plan",
    timestamp: "2026-03-04T12:30:00",
    userId: "u17",
    userName: "Nithya Ganesh",
  },
  {
    id: "a7",
    action: "user_registered",
    description: "New user registered",
    timestamp: "2026-03-03T08:10:00",
    userId: "u21",
    userName: "Revathi Sundaresan",
  },
  {
    id: "a8",
    action: "verification_approved",
    description: "Identity verification approved",
    timestamp: "2026-03-02T15:45:00",
    userId: "u22",
    userName: "Balaji Natarajan",
  },
];

/* ============================================================
   Store
   ============================================================ */

interface AdminState {
  admin: AdminUser;
  users: UserRecord[];
  verificationRequests: VerificationRequest[];
  reports: Report[];
  subscriptions: Subscription[];
  stats: AdminStats;
  activityLog: ActivityLogEntry[];

  // User actions
  banUser: (userId: string) => void;
  suspendUser: (userId: string) => void;
  activateUser: (userId: string) => void;
  makePremium: (userId: string) => void;
  downgradeToFree: (userId: string) => void;

  // Verification actions
  approveVerification: (requestId: string) => void;
  rejectVerification: (requestId: string, reason: string) => void;

  // Report actions
  resolveReport: (reportId: string, resolution: string) => void;
  dismissReport: (reportId: string) => void;
}

export const useAdminStore = create<AdminState>((set) => ({
  admin: {
    id: "admin1",
    name: "Admin User",
    email: "admin@thirumangalyam.com",
    role: "super_admin",
    lastLogin: "2026-03-09T08:00:00",
  },
  users: mockUsers,
  verificationRequests: mockVerifications,
  reports: mockReports,
  subscriptions: mockSubscriptions,
  stats: mockStats,
  activityLog: mockActivity,

  banUser: (userId) =>
    set((state) => ({
      users: state.users.map((u) =>
        u.id === userId ? { ...u, status: "banned" as const } : u
      ),
    })),

  suspendUser: (userId) =>
    set((state) => ({
      users: state.users.map((u) =>
        u.id === userId ? { ...u, status: "suspended" as const } : u
      ),
    })),

  activateUser: (userId) =>
    set((state) => ({
      users: state.users.map((u) =>
        u.id === userId ? { ...u, status: "active" as const } : u
      ),
    })),

  makePremium: (userId) =>
    set((state) => ({
      users: state.users.map((u) =>
        u.id === userId ? { ...u, plan: "premium_6" as const } : u
      ),
    })),

  downgradeToFree: (userId) =>
    set((state) => ({
      users: state.users.map((u) =>
        u.id === userId ? { ...u, plan: "free" as const } : u
      ),
    })),

  approveVerification: (requestId) =>
    set((state) => ({
      verificationRequests: state.verificationRequests.map((v) =>
        v.id === requestId
          ? { ...v, status: "approved" as const, reviewedAt: new Date().toISOString() }
          : v
      ),
      stats: {
        ...state.stats,
        pendingVerifications: state.stats.pendingVerifications - 1,
      },
    })),

  rejectVerification: (requestId, reason) =>
    set((state) => ({
      verificationRequests: state.verificationRequests.map((v) =>
        v.id === requestId
          ? {
              ...v,
              status: "rejected" as const,
              reviewedAt: new Date().toISOString(),
              rejectionReason: reason,
            }
          : v
      ),
      stats: {
        ...state.stats,
        pendingVerifications: state.stats.pendingVerifications - 1,
      },
    })),

  resolveReport: (reportId, resolution) =>
    set((state) => ({
      reports: state.reports.map((r) =>
        r.id === reportId
          ? {
              ...r,
              status: "resolved" as const,
              resolvedAt: new Date().toISOString(),
              resolution,
            }
          : r
      ),
      stats: { ...state.stats, openReports: state.stats.openReports - 1 },
    })),

  dismissReport: (reportId) =>
    set((state) => ({
      reports: state.reports.map((r) =>
        r.id === reportId
          ? { ...r, status: "dismissed" as const, resolvedAt: new Date().toISOString() }
          : r
      ),
      stats: { ...state.stats, openReports: state.stats.openReports - 1 },
    })),
}));
